#./DYdraw.py -c <cut> -w <weight> -b <binning> -p <plotvar> -x <x-name> -y <y_name> -f <f_name> -d <dolog> 

std_cut     = 'Dilep.M()>60'

BDT_cut     = ''

weight      = 'genweight*puweight*mueffweight*btagweight'
#weight      = 'genweight*puweight*mueffweight'

json_used   = 'Golden'

x_name_l    = ["Invariant Mass [GeV]", "Transverse Momentum [GeV]"]

plotvar_l   = ["dilep.M\(\)", "dilep.Pt\(\)"]

binset_l    = ["[300,0,300]", "[250,0,300]", "[200,0,300]", "[150,0,300]"]

MCat_l      = ["VBFT_M", "GGFT_M", "VBFL_M", "JetT_M", "JetL_M"]

PTCat_l     = ["VBFT_Pt", "GGFT_Pt", "VBFL_Pt", "JetT_Pt", "JetL_Pt"] 

lst         = []

User_input = raw_input(" How would you like it listed? valid, FL, FH, SL, cut, XL, Out, nFH, nonb : ") 
if User_input == "nonb":
   std_cut = 'Dilep.M()>60&&nonB==1&&MVA_BDTnoB>0.0950'
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [75,50,200] -p 'Dilep.M()' -x 'm(\mu^+\mu^-)GeV' -y 'Event/2 GeV' -f 'nonB_Dilept_M_BDT' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   std_cut = 'Dilep.M()>60&&nonB==1'
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [75,50,200] -p 'Dilep.M()' -x 'm{(\mu^+\mu^-)}GeV' -y 'Event/2 GeV' -f 'nonB_Dilept_M' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   std_cut = 'Dilep.M()>60&&nonB==1'
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [75,0,300] -p 'Dilep.Pt()' -x 'p_T(\mu^+\mu^-)GeV' -y 'Event' -f 'nonB_Dilept_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [45,0,200] -p 'Mu1.Pt()' -x '\[p_T(\mu_1)GeV\]' -y 'Event' -f 'nonB_lept1_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,-2.5,2.5] -p 'Mu1.Eta()' -x '\[\eta(\mu_1)\]' -y 'Event' -f 'nonB_lept1_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [45,0,200] -p 'Mu2.Pt()' -x '\[p_t(\mu_2)\]GeV' -y 'Event' -f 'nonB_lept2_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,-2.5,2.5] -p 'Mu2.Eta()' -x '\[\eta(\mu_2)\]' -y 'Event' -f 'nonB_lept2_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'njet' -x 'nJets' -y 'Event' -f 'nonB_NJets' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nbjet' -x 'nBJets' -y 'Event' -f 'nonB_NBMJet' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nelec' -x 'nElec' -y 'Event' -f 'nonB_nElec' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nmuon' -x 'nMuon' -y 'Event' -f 'nonB_nExtraMu' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nlep' -x 'nLep' -y 'Event' -f 'nonB_nLep' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,0,300] -p 'Met' -x '\[E_T^miss\]GeV' -y 'Event' -f 'nonB_MET' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,0.8484,1.05] -p 'CSVv2' -x 'CSVv2-Medium' -y 'Event' -f 'nonB_CSVv2' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,-3.2,3.2] -p 'Met_phi' -x 'MET_phi' -y 'Event' -f 'nonB_MET_phi' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,301] -p 'DijetM1' -x 'DijetM1' -y 'Event' -f 'nonB_DiJetM1' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,301] -p 'DijetM2' -x 'DijetM2' -y 'Event' -f 'nonB_DiJetM2' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [60,-4.7,4.7] -p 'DijetEta1' -x 'DiJetEta1' -y 'Event' -f 'nonB_DiJet_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [60,-4.7,4.7] -p 'DijetEta2' -x 'DiJetEta2' -y 'Event' -f 'nonB_DiJet2_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   

if User_input == "Out":
   std_cut = 'Dilep.M()>60&&Out==1'
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [75,50,200] -p 'Dilep.M()' -x 'm(\mu^+\mu^-)GeV' -y 'Event/2 GeV' -f 'Out_Dilept_M' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   std_cut = 'Dilep.M()>60&&Out==1&&MVA_BDTOut>-0.0660'
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [75,50,200] -p 'Dilep.M()' -x 'm(\mu^+\mu^-)GeV' -y 'Event/2 GeV' -f 'Out_Dilept_M_BDT' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   std_cut = 'Dilep.M()>60&&Out==1'
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [75,0,300] -p 'Dilep.Pt()' -x 'p_T(\mu^+\mu^-)GeV' -y 'Event' -f 'Out_Dilept_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [45,0,200] -p 'Mu1.Pt()' -x '\[p_T(\mu_1)GeV\]' -y 'Event' -f 'Out_lept1_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,-2.5,2.5] -p 'Mu1.Eta()' -x '\[\eta(\mu_1)\]' -y 'Event' -f 'Out_lept1_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [45,0,200] -p 'Mu2.Pt()' -x '\[p_t(\mu_2)\]GeV' -y 'Event' -f 'Out_lept2_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,-2.5,2.5] -p 'Mu2.Eta()' -x '\[\eta(\mu_2)\]' -y 'Event' -f 'Out_lept2_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'njet' -x 'nJets' -y 'Event' -f 'Out_NJets' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nbjet' -x 'nBJets' -y 'Event' -f 'Out_NBMJet' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nelec' -x 'nElec' -y 'Event' -f 'Out_nElec' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nmuon' -x 'nMuon' -y 'Event' -f 'Out_nExtraMu' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nlep' -x 'nLep' -y 'Event' -f 'Out_nLep' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,0,300] -p 'Met' -x '\[E_T^miss\]GeV' -y 'Event' -f 'Out_MET' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,0.8484,1.05] -p 'CSVv2' -x 'CSVv2-Medium' -y 'Event' -f 'Out_CSVv2' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,-3.2,3.2] -p 'Met_phi' -x 'MET_phi' -y 'Event' -f 'Out_MET_phi' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   

if User_input == "nFH":
   std_cut = 'Dilep.M()>60&&nFH4==1&&MVA_BDTFH>0.0648'
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [75,50,200] -p 'Dilep.M()' -x 'm(\mu^+\mu^-)GeV' -y 'Event/2' -f 'nFH4_Dilept_M_BDT_test' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   std_cut = 'Dilep.M()>60&&nFH4==1'
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [60,50,200] -p 'Dilep.M()' -x 'm(\mu^+\mu^-)GeV' -y 'Event/2' -f 'nFH4_Dilept_M' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   std_cut = 'Dilep.M()>60&&nFH4==1'
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [75,0,300] -p 'Dilep.Pt()' -x 'p_T(\mu^+\mu^-)GeV' -y 'Event/2 Gev' -f 'nFH4_Dilept_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [45,0,200] -p 'Mu1.Pt()' -x '\[p_T(\mu_1)GeV\]' -y 'Event/2 Gev' -f 'nFH4_lept1_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,-2.5,2.5] -p 'Mu1.Eta()' -x '\[\eta(\mu_1)\]' -y 'Event' -f 'nFH4_lept1_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [45,0,200] -p 'Mu2.Pt()' -x '\[p_t(\mu_2)\]GeV' -y 'Event' -f 'nFH4_lept2_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,-2.5,2.5] -p 'Mu2.Eta()' -x '\[\eta(\mu_2)\]' -y 'Event' -f 'nFH4_lept2_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'njet' -x 'nJets' -y 'Event' -f 'nFH4_NJets' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nbjet' -x 'nBJets' -y 'Event' -f 'nFH4_NBMJet' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nelec' -x 'nElec' -y 'Event' -f 'nFH4_nElec' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nmuon' -x 'nMuon' -y 'Event' -f 'nFH4_nExtraMu' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nlep' -x 'nLep' -y 'Event' -f 'nFH4_nLep' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,0,300] -p 'Met' -x '\[E_T^miss\]GeV' -y 'Event' -f 'nFH4_MET' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,0.8484,1.05] -p 'CSVv2' -x 'CSVv2-Medium' -y 'Event' -f 'nFH4_CSVv2' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,-3.2,3.2] -p 'Met_phi' -x 'MET_phi' -y 'Event' -f 'nFH4_MET_phi' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [100,0,400] -p 'Jet_pt' -x 'jet_pT' -y 'Event' -f 'nFH4_Jet_pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [60,-4.7,4.7] -p 'Jet_eta' -x 'jet_Eta' -y 'Event' -f 'nFH4_Jet_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,-3.2,3.2] -p 'Jet_phi' -x 'jet_Phi' -y 'Event' -f 'nFH4_Jet_phi' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)   
if User_input == "nFH2":
   std_cut = 'Dilep.M()>60&&nFH4==1'
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'Top1.M()' -x 'TopMass_Reco11' -y 'Event' -f 'TopM11' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'Top2.M()' -x 'TopMass_Reco12' -y 'Event' -f 'TopM12' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'Top3.M()' -x 'TopMass_Reco13' -y 'Event' -f 'TopM13' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'Top4.M()' -x 'TopMass_Reco14' -y 'Event' -f 'TopM14' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'Top5.M()' -x 'TopMass_Reco15' -y 'Event' -f 'TopM15' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'Top6.M()' -x 'TopMass_Reco16' -y 'Event' -f 'TopM16' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'Top7.M()' -x 'TopMass_Reco21' -y 'Event' -f 'TopM21' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'Top8.M()' -x 'TopMass_Reco22' -y 'Event' -f 'TopM22' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'Top9.M()' -x 'TopMass_Reco23' -y 'Event' -f 'TopM23' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'Top10.M()' -x 'TopMass_Reco24' -y 'Event' -f 'TopM24' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'Top11.M()' -x 'TopMass_Reco25' -y 'Event' -f 'TopM25' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'Top12.M()' -x 'TopMass_Reco26' -y 'Event' -f 'TopM26' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,301] -p 'DiJetM1.M()' -x 'W_m1' -y 'Event' -f 'W_m1' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,301] -p 'DiJetM2.M()' -x 'W_m2' -y 'Event' -f 'W_m2' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,301] -p 'DiJetM3.M()' -x 'W_m3' -y 'Event' -f 'W_m3' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,301] -p 'DiJetM4.M()' -x 'W_m4' -y 'Event' -f 'W_m4' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,301] -p 'DiJetM5.M()' -x 'W_m5' -y 'Event' -f 'W_m5' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,301] -p 'DiJetM6.M()' -x 'W_m6' -y 'Event' -f 'W_m6' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'm2_Top1.M()' -x 'm2_TopMass_Reco11' -y 'Event' -f 'model2_TopM11' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'm2_Top2.M()' -x 'm2_TopMass_Reco12' -y 'Event' -f 'model2_TopM12' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'm2_Top3.M()' -x 'm2_TopMass_Reco13' -y 'Event' -f 'model2_TopM13' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'm2_Top4.M()' -x 'm2_TopMass_Reco14' -y 'Event' -f 'model2_TopM14' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'm2_Top5.M()' -x 'm2_TopMass_Reco15' -y 'Event' -f 'model2_TopM15' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'm2_Top6.M()' -x 'm2_TopMass_Reco16' -y 'Event' -f 'model2_TopM16' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'm2_Top7.M()' -x 'm2_TopMass_Reco21' -y 'Event' -f 'model2_TopM21' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'm2_Top8.M()' -x 'm2_TopMass_Reco22' -y 'Event' -f 'model2_TopM22' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'm2_Top9.M()' -x 'm2_TopMass_Reco23' -y 'Event' -f 'model2_TopM23' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'm2_Top10.M()' -x 'm2_TopMass_Reco24' -y 'Event' -f 'model2_TopM24' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'm2_Top11.M()' -x 'm2_TopMass_Reco25' -y 'Event' -f 'model2_TopM25' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,601] -p 'm2_Top12.M()' -x 'm2_TopMass_Reco26' -y 'Event' -f 'model2_TopM26' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,401] -p 'best_m2_top1.M()' -x 'm2_Best_TopMass_Reco1' -y 'Event' -f 'best_m2_TopM1' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,401] -p 'best_m2_top2.M()' -x 'm2_Best_TopMass_Reco2' -y 'Event' -f 'best_m2_TopM2' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [80,1,401] -p 'best_m2_top1.Pt()' -x 'm2_Best_TopPt_Reco1' -y 'Event' -f 'best_m2_TopPt1' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [80,1,401] -p 'best_m2_top2.Pt()' -x 'm2_Best_TopPt_Reco2' -y 'Event' -f 'best_m2_TopPt2' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,401] -p 'best_Top1.M()' -x 'm1_Best_TopMass_Reco1' -y 'Event' -f 'best_m1_TopM1' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,401] -p 'best_Top2.M()' -x 'm1_Best_TopMass_Reco2' -y 'Event' -f 'best_m1_TopM2' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [80,1,401] -p 'best_Top1.Pt()' -x 'm1_Best_TopPt_Reco1' -y 'Event' -f 'best_m1_TopPt1' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [80,1,401] -p 'best_Top2.Pt()' -x 'm1_Best_TopPt_Reco2' -y 'Event' -f 'best_m1_TopPt2' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,301] -p 'DiJetM12' -x 'W_m12' -y 'Event' -f 'W_m12' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,301] -p 'DiJetM13' -x 'W_m13' -y 'Event' -f 'W_m13' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,301] -p 'DiJetM14' -x 'W_m14' -y 'Event' -f 'W_m14' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,301] -p 'DiJetM23' -x 'W_m23' -y 'Event' -f 'W_m23' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,301] -p 'DiJetM24' -x 'W_m24' -y 'Event' -f 'W_m24' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,1,301] -p 'DiJetM34' -x 'W_m34' -y 'Event' -f 'W_m34' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,-2.5,2.5] -p 'best_m2_top1.Eta()' -x 'm2_Best_TopEta_Reco1' -y 'Event' -f 'best_m2_TopEta1' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,-2.5,2.5] -p 'best_m2_top2.Eta()' -x 'm2_Best_TopEta_Reco2' -y 'Event' -f 'best_m2_TopEta2' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [60,0,6] -p 'bjetDR' -x 'bjetDR' -y 'Event' -f 'bjetDR' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   cmd ="./tthDraw.py -c '%s' -w '%s' -b [60,0,6] -p 'TopDR' -x 'TopDR' -y 'Event' -f 'TopDR' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
   lst.append(cmd)
   

if User_input == "XL":

    std_cut = 'Dilep.M()>60&&XL==1&&MVA_BDTXL>=0.0685'
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [75,50,200] -p 'Dilep.M()' -x 'm(\mu^+\mu^-)GeV' -y 'Event/2 GeV' -f 'XL_Dilept_M_BDT' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    std_cut = 'Dilep.M()>60&&XL==1'
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [60,50,200] -p 'Dilep.M()' -x 'm(\mu^+\mu^-)GeV' -y 'Event/2 GeV' -f 'XL_Dilept_M' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    std_cut = 'Dilep.M()>60&&XL==1'
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [60,0,300] -p 'Dilep.Pt()' -x 'p_T(\mu^+\mu^-)GeV' -y 'Event' -f 'XL_Dilept_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [45,0,200] -p 'Mu1.Pt()' -x '\[p_T(\mu_1)GeV\]' -y 'Event' -f 'XL_lept1_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,-2.5,2.5] -p 'Mu1.Eta()' -x '\[\eta(\mu_1)\]' -y 'Event' -f 'XL_lept1_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [45,0,200] -p 'Mu2.Pt()' -x '\[p_t(\mu_2)\]GeV' -y 'Event' -f 'XL_lept2_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,-2.5,2.5] -p 'Mu2.Eta()' -x '\[\eta(\mu_2)\]' -y 'Event' -f 'XL_lept2_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'njet' -x 'nJets' -y 'Event' -f 'XL_NJets' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nbjet' -x 'nBJets' -y 'Event' -f 'XL_NBMed' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nelec' -x 'nElec' -y 'Event' -f 'XL_nElec' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nmuon' -x 'nMuon' -y 'Event' -f 'XL_nExtraMu' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nlep' -x 'nLep' -y 'Event' -f 'XL_nLep' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,0,300] -p 'Met' -x '\[E_T^miss\]GeV' -y 'Event' -f 'XL_MET' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,0.8484,1.05] -p 'CSVv2' -x 'CSVv2-Medium' -y 'Event' -f 'XL_CSVv2' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,-3.2,3.2] -p 'Met_phi' -x 'MET_phi' -y 'Event' -f 'XL_MET_phi' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [20,0,4] -p 'minDR' -x 'MinDR' -y 'Event' -f 'XL_MinDR' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   

if User_input == "cut":

    cmd ="./tthsame.py -c '%s' -w '%s' -b [50,0,1] -p 'JetChemef' -x 'JetChemef' -y 'Event' -f 'Jet_Chemef' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [50,0,1] -p 'JetChhef' -x 'JetChhef' -y 'Event' -f 'JetChhef' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [50,0,1] -p 'Jetneemef' -x 'Jetneemef' -y 'Event' -f 'Jetneemef' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [50,0,1] -p 'Jetnehef' -x 'Jetnehef' -y 'Event' -f 'Jetnehef' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [50,0,1] -p 'Jetqgl' -x 'Jetqgl' -y 'Event' -f 'Jetqgl' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [60,0,120] -p 'JetM' -x 'JetM' -y 'Event' -f 'JetM' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [200,0,800] -p 'Jetpt' -x 'Jetpt' -y 'Event' -f 'Jetpt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [50,-4.7,4.7] -p 'Jeteta' -x 'Jeteta' -y 'Event' -f 'Jeteta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [30,0.2,0.8] -p 'Jetarea' -x 'Jetarea' -y 'Event' -f 'Jetarea' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [40,0,80] -p 'JetConst' -x 'JetConst' -y 'Event' -f 'JetConst' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [100,0,460] -p 'Jetptreg' -x 'Jetptreg' -y 'Event' -f 'Jetptreg' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [30,-0.15,0.15] -p 'Mudxy' -x 'Mudxy' -y 'Event' -f 'Mudxy' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [30,-0.2,0.2] -p 'Mudz' -x 'Mudz' -y 'Event' -f 'Mudz' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [30,0,0.25] -p 'Muip3d' -x 'Muip3d' -y 'Event' -f 'Muip3d' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [30,0,0.25] -p 'MuminiPFall' -x 'MuminiPFall' -y 'Event' -f 'MuminiPFall' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [30,0,0.25] -p 'MuminiPFchg' -x 'MuminiPFchg' -y 'Event' -f 'MuminiPFchg' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [30,0,0.25] -p 'Mupf03all' -x 'Mupf03all' -y 'Event' -f 'Mupf03all' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [30,0,0.25] -p 'Mupf03chg' -x 'Mupf03chg' -y 'Event' -f 'Mupf03chg' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [30,0,0.25] -p 'Mupf04all' -x 'Mupf04all' -y 'Event' -f 'Mupf04all' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [50,0,1] -p 'MuSegComp' -x 'MuSegComp' -y 'Event' -f 'MuSegComp' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [50,-0.3,0.3] -p 'elecdxy' -x 'elecdxy' -y 'Event' -f 'elecdxy' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [50,-0.3,0.3] -p 'elecdz' -x 'elecdz' -y 'Event' -f 'elecdz' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [50,-0.2,0.03] -p 'eleceinvm' -x 'eleceinvm' -y 'Event' -f 'eleceinvm' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [50,0,0.1] -p 'elechoe' -x 'elechoe' -y 'Event' -f 'elechoe' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [30,0,0.2] -p 'elecip3d' -x 'elecip3d' -y 'Event' -f 'elecip3d' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthsame.py -c '%s' -w '%s' -b [50,0.2,1.1] -p 'elecr9' -x 'b_elecr9' -y 'Event' -f 'b_elecr9' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   

if User_input == "valid":

    std_cut = 'Dilep.M()>60'
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [75,50,200] -p 'Dilep.M()' -x 'm(\mu^+\mu^-) GeV' -y 'Event/2 GeV' -f 'Dilept_M' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    std_cut = 'Dilep.M()>60&&nbjet==1'
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [75,50,200] -p 'Dilep.M()' -x 'm(\mu^+\mu^-)GeV' -y 'Event/2' -f 'Dilept_M_1b' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    std_cut = 'Dilep.M()>60&&nbjet==0'
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [75,50,200] -p 'Dilep.M()' -x 'm(\mu^+\mu^-)GeV' -y 'Event/2' -f 'Dilept_M_nob' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    std_cut = 'Dilep.M()>60'
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [60,0,300] -p 'Dilep.Pt()' -x 'p_T(\mu^+\mu^-)GeV' -y 'Event' -f 'Dilept_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,0,200] -p 'Mu1.Pt()' -x '\[p_T(\mu_1)GeV\]' -y 'Event' -f 'lept1_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,-2.5,2.5] -p 'Mu1.Eta()' -x '\[\eta(\mu_1)\]' -y 'Event' -f 'lept1_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,0,200] -p 'Mu2.Pt()' -x '\[p_t(\mu_2)\]GeV' -y 'Event' -f 'lept2_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,-2.5,2.5] -p 'Mu2.Eta()' -x '\[\eta(\mu_2)\]' -y 'Event' -f 'lept2_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'njet' -x 'nJets' -y 'Event' -f 'NJets' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nbjet' -x 'nBJets' -y 'Event' -f 'NBMed' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nelec' -x 'nElec' -y 'Event' -f 'nElec' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nmuon' -x 'nMuon' -y 'Event' -f 'nMu' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nlep' -x 'nLep' -y 'Event' -f 'nLep' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,0,300] -p 'Met' -x '\[E_T^miss\]GeV' -y 'Event' -f 'MET' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,0.8484,1.05] -p 'CSVv2' -x 'CSVv2-Medium' -y 'Event' -f 'CSVv2' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,-3.2,3.2] -p 'Met_phi' -x 'MET_phi' -y 'Event' -f 'MET_phi' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [100,0,400] -p 'Jet_pt' -x 'jet_pT' -y 'Event' -f 'Jet_pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [60,-4.7,4.7] -p 'Jet_eta' -x 'jet_Eta' -y 'Event' -f 'Jet_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,-3.2,3.2] -p 'Jet_phi' -x 'jet_Phi' -y 'Event' -f 'Jet_phi' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [100,0,400] -p 'nonbJet_pt' -x 'nonbjet_pT' -y 'Event' -f 'nonbJet_pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [60,-4.7,4.7] -p 'nonbJet_eta' -x 'nonbjet_Eta' -y 'Event' -f 'nonbJet_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,-3.2,3.2] -p 'nonbJet_phi' -x 'nonbjet_Phi' -y 'Event' -f 'nonbJet_phi' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [60,-4.7,4.7] -p 'Jet_eta1' -x 'jet_Eta1' -y 'Event' -f 'Jet_eta1' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [60,-4.7,4.7] -p 'Jet_eta2' -x 'jet_Eta2' -y 'Event' -f 'Jet_eta2' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [60,-4.7,4.7] -p 'Jet_eta3' -x 'jet_Eta3' -y 'Event' -f 'Jet_eta3' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [60,-4.7,4.7] -p 'Jet_eta4' -x 'jet_Eta4' -y 'Event' -f 'Jet_eta4' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [100,0,400] -p 'bjet.Pt()' -x 'bjet_pT' -y 'Event' -f 'bJet_pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [60,-2.4,2.4] -p 'bjet.Eta()' -x 'bjet_Eta' -y 'Event' -f 'bJet_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,-3.2,3.2] -p 'bjet.Phi()' -x 'bjet_Phi' -y 'Event' -f 'bJet_phi' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
if User_input == "FL":

    std_cut = 'Dilep.M()>60&&FL==1&&njet>=1&&nbjet>=1'
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [75,50,200] -p 'Dilep.M()' -x 'm(\mu^+\mu^-)GeV' -y 'Event' -f 'FL_Dilept_M' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    std_cut = 'Dilep.M()>12&&FL==1&&njet>=1&&nbjet>=1'
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [60,0,300] -p 'Dilep.Pt()' -x 'p_T(\mu^+\mu^-)GeV' -y 'Event' -f 'FL_Dilept_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [45,0,200] -p 'Mu1.Pt()' -x '\[p_T(\mu_1)GeV\]' -y 'Event' -f 'FL_lept1_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,-2.5,2.5] -p 'Mu1.Eta()' -x '\[\eta(\mu_1)\]' -y 'Event' -f 'FL_lept1_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [45,0,200] -p 'Mu2.Pt()' -x '\[p_t(\mu_2)\]GeV' -y 'Event' -f 'FL_lept2_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,-2.5,2.5] -p 'Mu2.Eta()' -x '\[\eta(\mu_2)\]' -y 'Event' -f 'FL_lept2_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'njet' -x 'nJets' -y 'Event' -f 'FL_NJets' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nbjet' -x 'nBJets' -y 'Event' -f 'FL_NBMed' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nelec' -x 'nElec' -y 'Event' -f 'FL_nElec' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nmuon' -x 'nMuon' -y 'Event' -f 'FL_nExtraMu' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nlep' -x 'nLep' -y 'Event' -f 'FL_nLep' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,0,300] -p 'Met' -x '\[E_T^miss\]GeV' -y 'Event' -f 'FL_MET' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,0.8484,1.05] -p 'CSVv2' -x 'CSVv2-Medium' -y 'Event' -f 'FL_CSVv2' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,-3.2,3.2] -p 'Met_phi' -x 'MET_phi' -y 'Event' -f 'FL_MET_phi' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   

if User_input == "FH":
   for i in [2,3,4]: 
    std_cut = 'Dilep.M()>60&&FH%s==1'%i
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [75,50,200] -p 'Dilep.M()' -x 'm(\mu^+\mu^-)GeV' -y 'Event' -f 'FH%s_Dilept_M' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight, i)
    lst.append(cmd)   
    std_cut = 'Dilep.M()>12&&FH%s==1'%i
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [75,0,300] -p 'Dilep.Pt()' -x 'p_T(\mu^+\mu^-)GeV' -y 'Event' -f 'FH%s_Dilept_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight, i)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [45,0,200] -p 'Mu1.Pt()' -x '\[p_T(\mu_1)GeV\]' -y 'Event' -f 'FH%s_lept1_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight, i)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,-2.5,2.5] -p 'Mu1.Eta()' -x '\[\eta(\mu_1)\]' -y 'Event' -f 'FH%s_lept1_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight, i)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [45,0,200] -p 'Mu2.Pt()' -x '\[p_t(\mu_2)\]GeV' -y 'Event' -f 'FH%s_lept2_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight, i)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,-2.5,2.5] -p 'Mu2.Eta()' -x '\[\eta(\mu_2)\]' -y 'Event' -f 'FH%s_lept2_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight, i)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'njet' -x 'nJets' -y 'Event' -f 'FH%s_NJets' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight, i)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nbjet' -x 'nBJets' -y 'Event' -f 'FH%s_NBMJet' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight, i)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nelec' -x 'nElec' -y 'Event' -f 'FH%s_nElec' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight, i)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nmuon' -x 'nMuon' -y 'Event' -f 'FH%s_nExtraMu' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight, i)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nlep' -x 'nLep' -y 'Event' -f 'FH%s_nLep' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight, i)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,0,300] -p 'Met' -x '\[E_T^miss\]GeV' -y 'Event' -f 'FH%s_MET' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight, i)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,0.8484,1.05] -p 'CSVv2' -x 'CSVv2-Medium' -y 'Event' -f 'FH%s_CSVv2' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight, i)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,-3.2,3.2] -p 'Met_phi' -x 'MET_phi' -y 'Event' -f 'FH%s_MET_phi' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight, i)
    lst.append(cmd)   

if User_input == "SL":

    std_cut = 'Dilep.M()>60&&SL==1'
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [75,50,200] -p 'Dilep.M()' -x 'm(\mu^+\mu^-)GeV' -y 'Event' -f 'SL_Dilept_M' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    std_cut = 'Dilep.M()>12&&SL==1'
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [60,0,300] -p 'Dilep.Pt()' -x 'p_T(\mu^+\mu^-)GeV' -y 'Event' -f 'SL_Dilept_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [45,0,200] -p 'Mu1.Pt()' -x '\[p_T(\mu_1)GeV\]' -y 'Event' -f 'SL_lept1_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,-2.5,2.5] -p 'Mu1.Eta()' -x '\[\eta(\mu_1)\]' -y 'Event' -f 'SL_lept1_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [45,0,200] -p 'Mu2.Pt()' -x '\[p_t(\mu_2)\]GeV' -y 'Event' -f 'SL_lept2_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,-2.5,2.5] -p 'Mu2.Eta()' -x '\[\eta(\mu_2)\]' -y 'Event' -f 'SL_lept2_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'njet' -x 'nJets' -y 'Event' -f 'SL_NJets' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nbjet' -x 'nBJets' -y 'Event' -f 'SL_NBMed' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nelec' -x 'nElec' -y 'Event' -f 'SL_nElec' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nmuon' -x 'nMuon' -y 'Event' -f 'SL_nExtraMu' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'nlep' -x 'nLep' -y 'Event' -f 'SL_nLep' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,0,300] -p 'Met' -x '\[E_T^miss\]GeV' -y 'Event' -f 'SL_MET' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,0.8484,1.05] -p 'CSVv2' -x 'CSVv2-Medium' -y 'Event' -f 'SL_CSVv2' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   
    cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,-3.2,3.2] -p 'Met_phi' -x 'MET_phi' -y 'Event' -f 'SL_MET_phi' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
    lst.append(cmd)   


for l in lst:
    print l
  #  cmd ="./tthDraw.py -c '%s' -w '%s' -b [45,0,200] -p 'jet1.Pt()' -x '\[p_t(j\_1)\]GeV' -y 'Event' -f 'jet1_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
  #  lst.append(cmd)   
  #  cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,-5,5] -p 'jet1.Eta()' -x '\[\eta(j\_1)\]' -y 'Event' -f 'jet1a_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
  #  lst.append(cmd)   
  #  cmd ="./tthDraw.py -c '%s' -w '%s' -b [45,0,200] -p 'jet2.Pt()' -x '\[p_t(j\_2)\]GeV' -y 'Event' -f 'jet2_Pt' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
  #  lst.append(cmd)   
  #  cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,-5,5] -p 'jet2.Eta()' -x '\[\eta(j\_2)\]' -y 'Event' -f 'jet2_eta' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
  #  lst.append(cmd)   
  # if User_input =="BDT":
  #     cmd ="./tthDraw.py -c '%s' -w '%s' -b [150,50,200] -p 'Dilep.M()' -x 'm(\mu^+\mu^-)GeV' -y 'Event' -f 'Dilept_M' -j 'Golden' -d 'True' > /dev/null &"%(std_cut, weight)
  #     lst.append(cmd)   
  #     cmd ="./tthDraw.py -c '%s' -w '%s' -b [60,0,300] -p 'Dilep.Pt()' -x 'p_t(\mu^+\mu^-)GeV' -y 'Event' -f 'Dilept_Pt' -j 'Golden' -d 'True' > /dev/null &"%(BDT_cut, weight)
  #     lst.append(cmd)   
  #   #  cmd ="./tthDraw.py -c '%s' -w '%s' -b [52,0,150] -p 'met' -x '\[E_T^miss\]GeV' -y 'Event' -f 'MET' -j 'Golden' -d 'True' > /dev/null &"%(BDT_cut, weight)
  #   #  lst.append(cmd)   
  #     cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,-2.5,2.5] -p 'Dilep.Eta()' -x '\eta(\mu^+\mu^-)' -y 'Event' -f 'Dilept_Eta' -j 'Golden' -d 'True' > /dev/null &"%(BDT_cut, weight)
  #     lst.append(cmd)   
  #     cmd ="./tthDraw.py -c '%s' -w '%s' -b [12,0,5] -p 'Muetadiff' -x '|\Delta\eta(\mu^+\mu^-)|' -y 'Event' -f 'Mu_DeltaEta' -j 'Golden' -d 'True' > /dev/null &"%(BDT_cut, weight)
  #     lst.append(cmd)   
  #     cmd ="./tthDraw.py -c '%s' -w '%s' -b [25,0,3.2] -p 'Muphidiff' -x '|\Delta\phi(\mu^+\mu^-)|' -y 'Event' -f 'Mu_DeltaPhi' -j 'Golden' -d 'True' > /dev/null &"%(BDT_cut, weight)
  #     lst.append(cmd)   
  #     cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'central_jets' -x 'nJetsCent' -y 'Event' -f 'nJets_Cent' -j 'Golden' -d 'True' > /dev/null &"%(BDT_cut, weight)
  #     lst.append(cmd)   
  #     cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,0,2000] -p 'DijetM1' -x '\[m(jj\_1)\]' -y 'Event' -f 'Dijet_M1' -j 'Golden' -d 'True' > /dev/null &"%(BDT_cut, weight)
  #     lst.append(cmd)   
  #     cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,0,10] -p 'DijetEta1' -x '\[|\Delta\eta(jj\_1)|\]' -y 'Event' -f 'Dijet_Eta1' -j 'Golden' -d 'True' > /dev/null &"%(BDT_cut, weight)
  #     lst.append(cmd)   
  #     cmd ="./tthDraw.py -c '%s' -w '%s' -b [11,0,11] -p 'forward_jets' -x 'nJetsFwd' -y 'Event' -f 'nJets_Fwd' -j 'Golden' -d 'True' > /dev/null &"%(BDT_cut, weight)
  #     lst.append(cmd)   
  #     cmd ="./tthDraw.py -c '%s' -w '%s' -b [50,0,2000] -p 'DijetM2' -x '\[m(jj\_2)\]' -y 'Event' -f 'Dijet_M2' -j 'Golden' -d 'True' > /dev/null &"%(BDT_cut, weight)
  #     lst.append(cmd)   
  #     cmd ="./tthDraw.py -c '%s' -w '%s' -b [30,0,10] -p 'DijetEta2' -x '\[|\Delta\eta(jj\_2)|\]' -y 'Event' -f 'Dijet_Eta2' -j 'Golden' -d 'True' > /dev/null &"%(BDT_cut, weight)
  #  
  #  lst.append(cmd)   
